### ISSUE TITLE
How to analyze java in docker

### ISSUE THREAD

**Issue by RelaxJH-DouZhiR** [dynaroars/dig#39]
root@5e5853a00882:/dig/src# time ~/miniconda3/bin/python3  -O dig.py  /testaaa/tests/examples/Ex0.java
settings:INFO:2022-05-12 11:56:39.712264: dig.py /testaaa/tests/examples/Ex0.java
alg:INFO:analyzing '/testaaa/tests/examples/Ex0.java'
data.prog:ERROR:cmd '/usr/bin/java -cp /dig/src/java:/dig/src/java/asm-all-5.2.jar Instrument /var/tmp/dig_1637148626155009527_lbu2q4ig/delete_me/Ex0.class /var/tmp/dig_1637148626155009527_lbu2q4ig/delete_me/traces/Ex0.class /var/tmp/dig_1637148626155009527_lbu2q4ig/delete_me/symexe/Ex0.class' gives error
Error: Could not find or load main class Instrument
Caused by: java.lang.ClassNotFoundException: Instrument

Traceback (most recent call last):
  File "/dig/src/dig.py", line 272, in <module>
    dinvs = dig.start(seed=seed, maxdeg=args.maxdeg)
  File "/dig/src/alg.py", line 107, in start
    self.mysrc = self.mysrc_cls(self.filename, self.tmpdir_del)
  File "/dig/src/data/prog.py", line 268, in __init__
    cp = subprocess.run(
  File "/root/miniconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/java', '-cp', '/dig/src/java:/dig/src/java/asm-all-5.2.jar', 'Instrument', '/var/tmp/dig_1637148626155009527_lbu2q4ig/delete_me/Ex0.class', '/var/tmp/dig_1637148626155009527_lbu2q4ig/delete_me/traces/Ex0.class', '/var/tmp/dig_1637148626155009527_lbu2q4ig/delete_me/symexe/Ex0.class']' returned non-zero exit status 1.

**Comment by nguyenthanhvuh** [comment]
Hi, we'll work on putting Java support in the Docker.  You could always manually setup files required for running Java programs manually (essentially installing Java 8 and JPF).
