### ISSUE TITLE
Issue with setting up using Docker

### ISSUE THREAD

**Issue by yzhang54** [dynaroars/dig#44]
Hello Prof. Nguyen, 

Below is the setup error I got using Docker:

PS C:\Users\yulez> git clone --depth 1 https://github.com/dynaroars/dig.git
Cloning into 'dig'...
remote: Enumerating objects: 789, done.
remote: Counting objects: 100% (789/789), done.
remote: Compressing objects: 100% (652/652), done.
remote: Total 789 (delta 174), reused 544 (delta 119), pack-reused 0
Receiving objects: 100% (789/789), 13.01 MiB | 34.08 MiB/s, done.
Resolving deltas: 100% (174/174), done.
PS C:\Users\yulez> cd dig
PS C:\Users\yulez\dig> docker build . -t='dig'
[+] Building 212.3s (19/23)
 => [internal] load build definition from Dockerfile                                                     0.1s
 => => transferring dockerfile: 3.12kB                                                                   0.0s
 => [internal] load .dockerignore                                                                        0.1s
 => => transferring context: 2B                                                                          0.0s
 => [internal] load metadata for docker.io/library/debian:buster                                         1.4s
 => [ 1/20] FROM docker.io/library/debian:buster@sha256:e6fb8b88b411285ac71590459aa8d0a376acc86a3d17adf  5.9s
 => => resolve docker.io/library/debian:buster@sha256:e6fb8b88b411285ac71590459aa8d0a376acc86a3d17adfe4  0.0s
 => => sha256:e6fb8b88b411285ac71590459aa8d0a376acc86a3d17adfe45e806f522c54cc3 984B / 984B               0.0s
 => => sha256:1487e24b974ca8b859de513d40c7f30606949c1fa1e4057df81b2dc1915edc6a 529B / 529B               0.0s
 => => sha256:528ac3ebe42095912dc3c246715e7544a939c974532e2da1b93d2557a41c4567 1.46kB / 1.46kB           0.0s
 => => sha256:620af4e91dbf80032eee9f1ff66a8b04119d7a329b2a13e007d69c8a0b337bf0 50.45MB / 50.45MB         3.2s
 => => extracting sha256:620af4e91dbf80032eee9f1ff66a8b04119d7a329b2a13e007d69c8a0b337bf0                2.1s
 => [internal] load build context                                                                        2.4s
 => => transferring context: 31.65MB                                                                     2.3s
 => [ 2/20] RUN apt-get update -y                                                                        3.6s
 => [ 3/20] RUN apt-get install -y build-essential git software-properties-common emacs ocaml ocamlbu  131.9s
 => [ 4/20] RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh               6.1s
 => [ 5/20] RUN bash ./Miniconda3-latest-Linux-x86_64.sh -b                                             13.3s
 => [ 6/20] RUN /root/miniconda3/bin/conda install sympy pip -y                                         12.0s
 => [ 7/20] RUN /root/miniconda3/bin/pip3 install z3-solver                                              7.4s
 => [ 8/20] RUN /root/miniconda3/bin/pip3 install beartype                                               2.5s
 => [ 9/20] COPY . /dig                                                                                  0.2s
 => [10/20] WORKDIR /dig/EXTERNAL_FILES                                                                  0.0s
 => [11/20] RUN unzip develop.zip && mv cil-develop cil                                                  0.9s
 => [12/20] WORKDIR cil                                                                                  0.0s
 => [13/20] RUN ./configure && make                                                                     26.1s
 => [14/20] WORKDIR /dig/src/ocaml                                                                       0.0s
 => ERROR [15/20] RUN make clean; make                                                                   0.6s
------
 > [15/20] RUN make clean; make:
#19 0.584 rm -f *.cmo *.cmi *.d *.cmx *.dx *.o instr.exe
#19 0.586 rm -rf *.pyc *.pyo
#19 0.590 Makefile:1: *** Recursive variable 'OCAML_OPTIONS' references itself (eventually).  Stop.
------
executor failed running [/bin/sh -c make clean; make]: exit code: 2

**Comment by ferhaterata** [comment]
Hi,

I received the following error while docker building CIVL on Ubuntu 22.04.1 LTS x86_64.

Best,
~ Ferhat

```
docker build . -t='dig'
[+] Building 146.8s (18/22)                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                             0.0s
 => => transferring dockerfile: 2.96kB                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/debian:buster                                                                                 2.0s
 => [internal] load build context                                                                                                                0.3s
 => => transferring context: 31.64MB                                                                                                             0.3s
 => [ 1/19] FROM docker.io/library/debian:buster@sha256:233c3bbc892229c82da7231980d50adceba4db56a08c0b7053a4852782703459                         3.3s
 => => resolve docker.io/library/debian:buster@sha256:233c3bbc892229c82da7231980d50adceba4db56a08c0b7053a4852782703459                           0.0s
 => => sha256:acfe79482c3a2cbce0cecfec8f89b5121ab14597d882b38ef76b70efca7b2ac0 1.46kB / 1.46kB                                                   0.0s
 => => sha256:b2404786f3febb4866f85b0c8f52b0b0b94dfdb6543e94cd65f961c68f325ff7 50.45MB / 50.45MB                                                 1.6s
 => => sha256:233c3bbc892229c82da7231980d50adceba4db56a08c0b7053a4852782703459 984B / 984B                                                       0.0s
 => => sha256:b589ffbcc03bb272c9e0c0e699aedb2271a1ca65b2a3447057cbfd80d9eff9bf 529B / 529B                                                       0.0s
 => => extracting sha256:b2404786f3febb4866f85b0c8f52b0b0b94dfdb6543e94cd65f961c68f325ff7                                                        1.5s
 => [ 2/19] RUN apt-get update -y                                                                                                                3.1s
 => [ 3/19] RUN apt-get install -y build-essential git software-properties-common emacs ocaml ocamlbuild ocaml-findlib wget openjdk-11-jdk unz  86.3s
 => [ 4/19] RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh                                                       1.6s 
 => [ 5/19] RUN bash ./Miniconda3-latest-Linux-x86_64.sh -b                                                                                      6.8s 
 => [ 6/19] RUN /root/miniconda3/bin/conda install sympy pip -y                                                                                  7.8s 
 => [ 7/19] RUN /root/miniconda3/bin/pip3 install z3-solver beartype                                                                             3.9s 
 => [ 8/19] COPY . /dig                                                                                                                          0.1s 
 => [ 9/19] WORKDIR /dig/EXTERNAL_FILES                                                                                                          0.0s 
 => [10/19] RUN unzip develop.zip && mv cil-develop cil                                                                                          0.6s 
 => [11/19] WORKDIR cil                                                                                                                          0.0s 
 => [12/19] RUN ./configure && make                                                                                                             30.8s 
 => [13/19] WORKDIR /dig/src/ocaml                                                                                                               0.1s 
 => ERROR [14/19] RUN make clean; make                                                                                                           0.4s 
------                                                                                                                                                
 > [14/19] RUN make clean; make:                                                                                                                      
#0 0.372 rm -f *.cmo *.cmi *.d *.cmx *.dx *.o instr.exe                                                                                               
#0 0.374 rm -rf *.pyc *.pyo                                                                                                                           
#0 0.378 Makefile:1: *** Recursive variable 'OCAML_OPTIONS' references itself (eventually).  Stop.
------
Dockerfile:33
--------------------
  31 |     
  32 |     WORKDIR /dig/src/ocaml
  33 | >>> RUN make clean; make
  34 |     
  35 |     ## CIVL
--------------------
ERROR: failed to solve: process "/bin/sh -c make clean; make" did not complete successfully: exit code: 2

```

**Comment by nguyenthanhvuh** [comment]
Thanks for reporting.  I was able to reproduce this problem and fix it, but there are other issues arise mainly with Ocaml and Cil. Will try to find a work around as soon as I can.

**Comment by aniket-modi** [comment]
Hi

I received the following error while building on Ubuntu 20.04.5 LTS x86_64. 

docker build . -t='dig'
File "common.ml", line 1, characters 5-15:
Error: Unbound module GoblintCil
make: *** [Makefile:16: common.cmx] Error 2

Complete trace (rerun)
Sending build context to Docker daemon  32.24MB
Step 1/19 : FROM debian:buster
 ---> acfe79482c3a
Step 2/19 : RUN apt-get update -y
 ---> Using cache
 ---> bf5758f1e511
Step 3/19 : RUN apt-get install -y build-essential git software-properties-common emacs ocaml ocamlbuild ocaml-findlib wget openjdk-11-jdk unzip
 ---> Using cache
 ---> 88adb1373189
Step 4/19 : RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
 ---> Using cache
 ---> d32b696dbdbe
Step 5/19 : RUN bash ./Miniconda3-latest-Linux-x86_64.sh -b
 ---> Using cache
 ---> 267d6b9c313d
Step 6/19 : RUN /root/miniconda3/bin/conda install sympy pip -y
 ---> Using cache
 ---> b0bd83605887
Step 7/19 : RUN /root/miniconda3/bin/pip3 install z3-solver beartype
 ---> Using cache
 ---> 3c89e250ddf1
Step 8/19 : WORKDIR /
 ---> Using cache
 ---> bd611e606b6f
Step 9/19 : COPY . /dig
 ---> Using cache
 ---> 185f31231660
Step 10/19 : WORKDIR /dig/EXTERNAL_FILES
 ---> Using cache
 ---> 5583a67f244b
Step 11/19 : RUN unzip develop.zip && mv cil-develop cil
 ---> Using cache
 ---> 36c09313b91a
Step 12/19 : WORKDIR cil
 ---> Using cache
 ---> 19be1a7d7c33
Step 13/19 : RUN ./configure && make
 ---> Using cache
 ---> 4f9a4775ba3a
Step 14/19 : WORKDIR /dig/src/ocaml
 ---> Using cache
 ---> a001ab9d14ab
Step 15/19 : RUN make clean; make
 ---> Running in 44dec943d187
rm -f *.cmo *.cmi *.d *.cmx *.dx *.o instr.exe
rm -rf *.pyc *.pyo
ocamlopt                        -I /usr/lib/ocaml/goblint-cil/ -I /usr/lib/ocaml/zarith/  -c common.ml
File "common.ml", line 1, characters 5-15:
Error: Unbound module GoblintCil
make: *** [Makefile:16: common.cmx] Error 2

If there are some prospective fixes I can try on my end, please let me know.

Regards
Aniket

**Comment by nguyenthanhvuh** [comment]
Issue should be fixed with https://github.com/dynaroars/dig/commit/d5caabcbef2f3e561ac78a92629b5e1c527b0c5a
